services:
    austinmaddox.s3.listener:
        class: austinmaddox\s3\event\main_listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - %core.root_path%
        tags:
            - { name: event.listener }
